branches:
  only:
  - master
language: c
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
sudo: false
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.7
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.7
      - gcc-5
      - g++-5
      - firebird2.5-dev
     #- liballegro4.2-dev
      - libcairo2-dev
      - libcups2-dev
      - libcurl4-openssl-dev
      - libfreeimage-dev
      - libgd2-xpm-dev
      - libgpm-dev
     #- libgs-dev
      - libicu-dev
      - libmagic-dev
      - libmysqlclient-dev
      - libncurses5-dev
      - libpq-dev
     #- libslang2-dev
      - unixodbc-dev
script: export HB_COMPILER=$CC && make
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
       if [ "$CC" = "gcc" ]; then
          export HB_CCSUFFIX=-5;
          ls -lA /usr/bin/gcc*;
       else
          export HB_CCSUFFIX=-3.7;
          ls -lA /usr/bin/clang*;
       fi;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
       brew update > /dev/null;
       brew install cairo;
       brew install curl;
       brew install freeimage;
       brew install gd;
       brew install ghostscript;
       brew install icu4c;
       brew install libmagic;
       brew install mariadb;
       brew install openssl;
       brew install unixodbc;
    fi
notifications:
  email: false
git:
  submodules: false
